### ISSUE TITLE
Set up SolidOS to work on CSS on local development

### ISSUE THREAD

**Issue by timea-solid** [SolidOS/solidos#149]
In the process of switching NSS to CSS on solidcommunity.net I propose that we move our local development practices also to CSS. Basically when I clone SolidOS and I run `npm run setup` I would want to have CSS running and not NSS (if possible).

**Comment by ewingson** [comment]
cause I'm running CSS in a production environment and not local I am not really helpful in this topic. a) maybe the switch is an opportunity for me to contribute useful code. b) I *really* hope solidweb.me is hardened and stealthed enough.

**Comment by jeff-zucker** [comment]
Data-Kitchen is an instance of CSS local running SolidOS.  I have not updated to most recent versions of of CSS or mashlib and I need to revise the package.json to download them automatically.  But currently npm  install + nmp run start give you a functioning CSS running SolidOS on a local server.

**Comment by jeff-zucker** [comment]
A slight modification of the SolidOS build process could put Data-Kitchen into the build process so that instead of NSS at the end it would install CSS.

**Comment by jeff-zucker** [comment]
https://github.com/solid/data-kitchen/blob/main/assets/Data-Kitchen.png

**Comment by theRealImy** [comment]
@ewingson did first try to deploy SolidOS on a CSS server on https://solidweb.me. We see some problems which we will make gitIssues for.

**Comment by ewingson** [comment]
I have 4.0.0 running and will share every issue and every aspect I can focus on to help to upgrade `solidcommunity.net` . recipe working.

**Comment by angelo-v** [comment]
This is the docker-compose file I am using for locally running CSS with mashlib:

```
version: '3.7'
services:
  server:
    image: solidproject/community-server:4
    pull_policy: always
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./data:/opt/solid/data
      - ./config:/opt/solid/config
      - /path/to/local/mashlib:/opt/solid/mashlib

    command: ["--port", "3000" ,"-c" ,"/opt/solid/config/mashlib.json", "--rootFilePath", "/opt/solid/data" ]
```

`config/mashlib.json` is from [the CSS recipe](https://github.com/CommunitySolidServer/Recipes/blob/main/mashlib/config-mashlib.json) but you have to adjust the mashlib pathes for docker from `./node_modules/mashlib` to `/opt/solid/mashlib/`
